### ISSUE TITLE
`mutable.Map` does now work like `Map`

### ISSUE THREAD

**Issue by arteme** [sfxcode/pebble-scala#36]
Consider the following example:
```
import com.sfxcode.templating.pebble.ScalaPebbleEngine
import scala.collection.mutable

val engine = ScalaPebbleEngine(useStringLoader = true)

val map = Map("one" -> "1", "two" -> "2", "three" -> "3")
val context = Map("map" -> map)

val result = engine.evaluateToString("{{ map.values }}", context)
println(result)
```

The output is:
```
Iterable(1, 2, 3)
```

Now, if we replace `val map = Map("one" -> "1", "two" -> "2", "three" -> "3")` with `val map = mutable.Map("one" -> "1", "two" -> "2", "three" -> "3")`, the following exception is thrown:
```
java.lang.ExceptionInInitializerError
	at Main$.&lt;clinit&gt;(main.scala:16)
	at Main.main(main.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.Run.invokeMain(Run.scala:143)
	at sbt.Run.execute$1(Run.scala:93)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:120)
	at sbt.Run$.executeSuccess(Run.scala:186)
	at sbt.Run.runWithLoader(Run.scala:120)
	at sbt.Run.run(Run.scala:127)
	at com.olegych.scastie.sbtscastie.SbtScastiePlugin$$anon$1.$anonfun$run$1(SbtScastiePlugin.scala:38)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:21)
	at sbt.ScastieTrapExit$App.run(ScastieTrapExit.scala:258)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NumberFormatException: For input string: &quot;values&quot;
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at scala.collection.StringOps$.toInt$extension(StringOps.scala:908)
	at com.sfxcode.templating.pebble.extension.ScalaResolver.resolve(ScalaResolver.scala:22)
	at io.pebbletemplates.pebble.node.expression.GetAttributeExpression.evaluate(GetAttributeExpression.java:83)
	at io.pebbletemplates.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:66)
	at io.pebbletemplates.pebble.node.PrintNode.render(PrintNode.java:37)
	at io.pebbletemplates.pebble.node.BodyNode.render(BodyNode.java:44)
	at io.pebbletemplates.pebble.node.RootNode.render(RootNode.java:31)
	at io.pebbletemplates.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:157)
        ...
```

See the example here: https://scastie.scala-lang.org/YkFPnlmjS02TM5tEAMlGqQ

**Comment by sfxcode** [comment]
Fixed in Version 1.1.3
